version: '3.1'

services: 
    nginx-proxy:
        container_name: nginx
        image: jwilder/nginx-proxy
        restart: "always"
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx/vhost/:/etc/nginx/vhost.d:ro
            - ./nginx/conf.d/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
            - ./static/:/gamevaultcasino/static
            - ./nginx/.htpasswd:/gamevaultcasino/nginx/.htpasswd
            - ./media/:/gamevaultcasino/media
            - ./nginx/proxy.conf/:/etc/nginx/proxy.conf

    postgres:
        container_name: db
        image: postgres:9.6.6
        restart: always
        volumes:
            - ./pgdb/:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        env_file: ./.env


    web:
        container_name: gamevaultcasino
        build: .
        restart: "always"
        ports:
            - "8000:8000"

        volumes:
            - .:/code/
            # - ./static/:/code/static
            # - ./media/:/code/media
        depends_on:
            - "postgres"
        env_file: ./.env

   
networks:
    default:
        external:
            name: nginx-proxy